entrypoint script update
- Display container info in develop mode
- Added env vars: GIT_CHECKOUT, GIT_MERGE_PR, UNIT_TEST

diff --git a/php7.0/fpm/docker-oc-entrypoint b/php7.0/fpm/docker-oc-entrypoint
--- a/php7.0/fpm/docker-oc-entrypoint
+++ b/php7.0/fpm/docker-oc-entrypoint
@@ -1,6 +1,67 @@
 #!/bin/bash
 set -e
 
+# Display current commit, php version, and dependency info in develop mode
+if [ "${OCTOBERCMS_TAG,,}" == "develop" ]; then
+  if [ -d ".git" ]; then
+    echo -e "Develop October CMS\n---"
+    git log --pretty=format:"%s%n%C(yellow)%H%Creset" -1
+    echo -e "\n---"
+    php --version | grep PHP -m 1
+    composer info | grep october | awk '{print $1 ": " $2}'
+    echo "---"
+  fi
+fi
+
+# Checkout branch, tag, commit within the container
+if [ ! -z "$GIT_CHECKOUT" ]; then
+  if [ ! -d ".git" ]; then
+    error "Git repo is not found. Try the develop image" && exit 1;
+  fi
+  echo "Checking out $GIT_CHECKOUT...";
+  git checkout $GIT_CHECKOUT
+  git log --pretty=format:"%s%n%C(yellow)%H%Creset" -1
+  echo -e "\n---"
+fi
+
+# Pass GitHub pull request number to merge PR within the container for testing
+if [ ! -z "$GIT_MERGE_PR" ]; then
+  if [ ! -d ".git" ]; then
+    error "Git repo is not found. Try the develop image" && exit 1;
+  fi
+
+  echo "Test GitHub pull request #$GIT_MERGE_PR";
+  curl -fsS --connect-timeout 15 \
+    https://api.github.com/repos/octobercms/october/pulls/$GIT_MERGE_PR \
+    | jq -r '.title, .html_url';
+  echo "---"
+
+  echo "Fetch..."
+  git fetch origin pull/$GIT_MERGE_PR/head:pr-$GIT_MERGE_PR
+
+  echo "Merge..."
+  git merge --no-commit pr-$GIT_MERGE_PR || { error "Check if PR $GIT_MERGE_PR exists." && exit 1; }
+
+  echo "Diff..."
+  git diff --cached --stat
+  echo "---"
+fi
+
+# Runs all October CMS unit tests. Pass test filename to run a specific test.
+if [ ! -z "$UNIT_TEST" ]; then
+  echo -e "October CMS Unit Test..."
+  if [ "${UNIT_TEST,,}" == "true" ]; then
+    vendor/bin/phpunit
+  elif [ ! -f "$UNIT_TEST" ]; then
+    error "File '$UNIT_TEST' does not exist."
+  elif [ -f "$UNIT_TEST" ]; then
+    echo "Running single test: $UNIT_TEST"
+    vendor/bin/phpunit $UNIT_TEST
+  fi
+  echo "---"
+fi
+
+# Initialize vendor plugins where vendor folder isn't detected
 if [ "${INIT_PLUGINS,,}" == "true" ] || [ "${INIT_PLUGINS,,}" == "force" ]; then
   echo 'Initializing plugin vendor folders...'
   for i in $(echo plugins/*/*); do
@@ -14,12 +75,14 @@ if [ "${INIT_PLUGINS,,}" == "true" ] || [ "${INIT_PLUGINS,,}" == "force" ]; then
   done
 fi
 
+# Enable remote IP forwarding for proxy support
 if [[ "$1" == apache2* ]] && [ "${FWD_REMOTE_IP,,}" == "true" ]; then
   a2enmod remoteip -q
   echo 'RemoteIPHeader X-Forwarded-For' > $APACHE_CONFDIR/conf-available/docker-oc-apache.conf
   a2enconf docker-oc-apache -q
 fi
 
+# Start a cron process within the container
 if [ "${ENABLE_CRON,,}" == "true" ]; then
   php artisan schedule:run # required to prime db connection
   cron
@@ -28,6 +91,7 @@ elif [ "$1" == cron ]; then
   php artisan schedule:run
 fi
 
+# PHP config
 if [ ! -z "$PHP_DISPLAY_ERRORS" ]; then
   echo "php.ini set display_errors=$PHP_DISPLAY_ERRORS"
   sed -i "/display_errors=*/c\display_errors=$PHP_DISPLAY_ERRORS" /usr/local/etc/php/conf.d/docker-oc-php.ini
